import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#85f8c4",
        "on-secondary-fixed": "#001f29",
        "inverse-primary": "#93ccff",
        "on-primary-fixed": "#001d31",
        "surface-container-low": "#f2f3ff",
        "tertiary-container": "#00855d",
        "surface-dim": "#d2d9f4",
        "surface-variant": "#dae2fd",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#f5fff7",
        "secondary-fixed": "#b9eaff",
        "inverse-surface": "#283044",
        "on-surface-variant": "#3f4850",
        primary: "#006194",
        "inverse-on-surface": "#eef0ff",
        tertiary: "#006948",
        "surface-container-lowest": "#ffffff",
        outline: "#707881",
        secondary: "#006781",
        "tertiary-fixed-dim": "#68dba9",
        "on-background": "#131b2e",
        "secondary-fixed-dim": "#81d1f0",
        "on-primary-container": "#fdfcff",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#005137",
        error: "#ba1a1a",
        "primary-fixed-dim": "#93ccff",
        surface: "#faf8ff",
        "primary-container": "#007bb9",
        "on-error-container": "#93000a",
        "surface-container": "#eaedff",
        background: "#faf8ff",
        "on-error": "#ffffff",
        "outline-variant": "#bfc7d2",
        "on-surface": "#131b2e",
        "surface-tint": "#006398",
        "surface-bright": "#faf8ff",
        "primary-fixed": "#cce5ff",
        "secondary-container": "#8fdfff",
        "on-secondary-fixed-variant": "#004d62",
        "surface-container-highest": "#dae2fd",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#004b73",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#002114",
        "on-secondary-container": "#00647d",
        "surface-container-high": "#e2e7ff",
      },
      borderRadius: {
        sm: "0.5rem",
        DEFAULT: "1rem",
        md: "1.5rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1.5rem",
        "space-sm": "1rem",
        "space-xs": "0.5rem",
        "space-xl": "3rem",
        margin: "2.5rem",
        "space-lg": "2rem",
        "space-md": "1.5rem",
      },
      fontFamily: {
        "headline-md": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-xl": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-numeric": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "label-md": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["26px", { lineHeight: "36px", fontWeight: "600" }],
        "label-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-xl": ["22px", { lineHeight: "32px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-numeric": ["56px", { lineHeight: "64px", fontWeight: "800" }],
        "headline-xl": ["40px", { lineHeight: "52px", fontWeight: "700" }],
        "label-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "42px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
